In [4]:
import numpy as np
data = np.genfromtxt('./EIS_data.csv', delimiter=',')
for i in range(0,12):
    csv = data[:,[3*i,3*i+1,3*i+2]]
    fname = 'csv' + str(i) + '.txt'
    print(csv)
    np.savetxt(fname, csv, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)


[[1.0001951e+05 2.5573708e+02 2.3302980e+01]
 [7.9121078e+04 2.5796289e+02 2.0019239e+01]
 [6.2607406e+04 2.5959836e+02 1.6947983e+01]
 [4.9531234e+04 2.6108597e+02 1.4611738e+01]
 [3.9189441e+04 2.6257779e+02 1.2693474e+01]
 [3.1015619e+04 2.6325327e+02 1.0590907e+01]
 [2.4541012e+04 2.6408499e+02 8.9938116e+00]
 [1.9414059e+04 2.6476248e+02 7.6520004e+00]
 [1.5361323e+04 2.6523096e+02 6.6402149e+00]
 [1.2158199e+04 2.6581989e+02 5.5229521e+00]
 [9.7537256e+03 2.6634955e+02 5.1260886e+00]
 [7.7444312e+03 2.6685236e+02 4.5968399e+00]
 [6.1255767e+03 2.6678479e+02 4.5066767e+00]
 [4.7634761e+03 2.6766315e+02 4.0594335e+00]
 [3.7687942e+03 2.6755536e+02 3.8133225e+00]
 [2.9828621e+03 2.6816034e+02 4.0057964e+00]
 [2.3592412e+03 2.6841476e+02 4.2132792e+00]
 [1.8667950e+03 2.6911261e+02 4.1855092e+00]
 [1.4773607e+03 2.6941287e+02 4.8283420e+00]
 [1.1688768e+03 2.6991833e+02 5.2334638e+00]
 [9.2470642e+02 2.7051324e+02 5.6058183e+00]
 [7.3163953e+02 2.7114792e+02 6.3381801e+00]
 [5.790732